[workspace]
resolver = "2"
members = [
    "crates/hydra-core",
    "crates/hydra-cli",
]
exclude = ["crates/hydra-app"]
default-members = [
    "crates/hydra-core",
    "crates/hydra-cli",
]

[workspace.package]
edition = "2021"
license = "MIT"
